apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkins
  labels:
    app: mynginx
  name: mynginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
        - image: kamran420/nginx-test:latest
          name: nginx-test
          ports:
            - containerPort: 80
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mynginx
  name: mynginx
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 32400
  selector:
    app: mynginx
  sessionAffinity: None
